quoteProps: "as-needed"
semi: true
tabWidth: 3
useTabs: true
trailingComma: "es5"
importOrder: ["^@/app/(.*)$", "^[./]"]
importOrderSeparation: true
importOrderSortSpecifiers: true
plugins: ["@trivago/prettier-plugin-sort-imports"]
experimentalTernaries: true
